# Generated by Django 3.2.15 on 2022-08-18 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
