# Generated by Django 3.2.15 on 2022-08-20 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_book_book_author'),
        ('order', '0003_auto_20220820_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_lines', to='book.book'),
        ),
    ]
