# Generated by Django 3.2.15 on 2022-08-23 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_orderline_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='apply_once_per_customer',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='apply_once_per_order',
        ),
        migrations.AddField(
            model_name='voucher',
            name='discount_value_type',
            field=models.CharField(choices=[('fixed', 'đ'), ('percentage', '%')], default='fixed', max_length=10),
        ),
        migrations.AddField(
            model_name='voucher',
            name='type',
            field=models.CharField(choices=[('entire_order', 'Entire order'), ('shipping', 'Shipping'), ('specific_product', 'Specific products, collections and categories')], default='entire_order', max_length=20),
        ),
        migrations.AlterField(
            model_name='address',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
