# Generated by Django 3.2.15 on 2022-08-29 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20220824_0058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.RemoveField(
            model_name='orderline',
            name='tax_rate',
        ),
    ]
