# Generated by Django 3.2.15 on 2022-08-29 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20220829_1519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderline',
            old_name='product',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='orderline',
            old_name='product_name',
            new_name='book_name',
        ),
    ]
