# Generated by Django 3.2.15 on 2022-08-16 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0003_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.BigIntegerField(choices=[(0, 'Admin'), (1, 'Customer')], default=1, editable=False),
        ),
    ]
