# Generated by Django 3.2.15 on 2022-08-25 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaypalToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_type', models.CharField(blank=True, help_text='Identifies the type of token returned. At this time, this field will always have the value Bearer', max_length=255, null=True, verbose_name='Token Type')),
                ('access_token', models.CharField(help_text='The token that must be used to access the Core APIs', max_length=2048, verbose_name='Access Token')),
                ('refresh_token', models.CharField(blank=True, help_text='A token used when refreshing the access token', max_length=2048, null=True, verbose_name='Refresh Token')),
                ('expires_in', models.IntegerField(blank=True, help_text='The remaining lifetime of the access token in seconds. The value always returned is 3600 seconds (one hour). Use the refresh token to get a fresh one', null=True, verbose_name='Expires In')),
                ('refresh_token_expires_in', models.IntegerField(blank=True, help_text='The remaining lifetime, in seconds, for the connection, after which time the user must re-grant access.', null=True, verbose_name='Refresh Token Expires In')),
                ('scope', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('endpoint', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
