# Generated by Django 3.2.15 on 2022-08-26 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paypaltoken',
            options={'ordering': ['-createdAt']},
        ),
        migrations.CreateModel(
            name='PaypalOrder',
            fields=[
                ('paypal_order_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('approve_url', models.CharField(max_length=500, null=True)),
                ('capture_url', models.CharField(max_length=500, null=True)),
                ('token', models.CharField(max_length=50, null=True)),
                ('checkout', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='checkout.checkout')),
            ],
        ),
    ]
