# Generated by Django 3.2.15 on 2022-08-26 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20220826_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='paypalorder',
            name='link',
            field=models.TextField(null=True),
        ),
    ]
