# Generated by Django 3.2.15 on 2022-08-26 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_paypalorder_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paypalorder',
            old_name='link',
            new_name='links',
        ),
    ]
