# Generated by Django 3.2.15 on 2022-08-27 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
        ('payment', '0004_rename_link_paypalorder_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('address_line_1', models.CharField(max_length=255, null=True)),
                ('admin_area_2', models.CharField(max_length=255, null=True)),
                ('admin_area_1', models.CharField(max_length=255, null=True)),
                ('postal_code', models.CharField(max_length=255, null=True)),
                ('country_code', models.CharField(max_length=255, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('checkout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='checkout.checkout')),
                ('paypal_checkout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payment.paypalorder')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
    ]
