# Generated by Django 3.2.15 on 2022-08-28 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20220824_0058'),
        ('payment', '0006_rename_paypal_checkout_payment_paypal_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='order.order'),
        ),
    ]
