# Generated by Django 3.2.15 on 2022-08-29 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
        ('payment', '0007_payment_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='checkout',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='checkout.checkout'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paypal_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='payment.paypalorder'),
        ),
    ]
