# Generated by Django 3.2.15 on 2022-08-16 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_favoritelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritelist',
            name='books',
            field=models.ManyToManyField(to='book.Book'),
        ),
    ]
