# Generated by Django 3.2.15 on 2022-08-16 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_alter_favoritelist_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pricebook',
            field=models.BigIntegerField(),
        ),
    ]
