# Generated by Django 3.2.15 on 2022-08-28 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_auto_20220823_1958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='status',
            new_name='description',
        ),
        migrations.AddField(
            model_name='book',
            name='is_trend',
            field=models.BooleanField(default=False),
        ),
    ]
