# Generated by Django 3.2.15 on 2022-08-29 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_bookreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavoritelist',
            name='books',
            field=models.ManyToManyField(to='book.Book'),
        ),
    ]
